package exedev

import (
	"context"
	"time"

	p "github.com/pulumi/pulumi-go-provider"
	"github.com/pulumi/pulumi-go-provider/infer"
)

type Vm struct{}

type VmArgs struct {
	Name         *string           `pulumi:"name,optional"`
	Image        *string           `pulumi:"image,optional"`
	CPU          *int              `pulumi:"cpu,optional"`
	Memory       *string           `pulumi:"memory,optional"`
	Disk         *string           `pulumi:"disk,optional"`
	Tags         []string          `pulumi:"tags,optional"`
	Env          map[string]string `pulumi:"env,optional"`
	SetupScript  *string           `pulumi:"setupScript,optional"`
	Command      *string           `pulumi:"command,optional"`
	Comment      *string           `pulumi:"comment,optional"`
	Integrations []string          `pulumi:"integrations,optional"`
	Prompt       *string           `pulumi:"prompt,optional"`
	RegistryAuth *string           `pulumi:"registryAuth,optional" provider:"secret"`
	NoEmail      *bool             `pulumi:"noEmail,optional"`
	Public       *bool             `pulumi:"public,optional"`
	Port         *int              `pulumi:"port,optional"`
	ReceiveEmail *bool             `pulumi:"receiveEmail,optional"`
	TeamAccess   *bool             `pulumi:"teamAccess,optional"`
}

type VmState struct {
	VmArgs
	VMName        string `pulumi:"vmName"`
	HTTPSURL      string `pulumi:"httpsUrl"`
	SSHDest       string `pulumi:"sshDest"`
	Region        string `pulumi:"region"`
	RegionDisplay string `pulumi:"regionDisplay"`
	Status        string `pulumi:"status"`
	AllocatedCPUs int    `pulumi:"allocatedCpus"`
	MemoryBytes   int64  `pulumi:"memoryBytes"`
	DiskBytes     int64  `pulumi:"diskBytes"`
}

var (
	_ infer.CustomResource[VmArgs, VmState] = (*Vm)(nil)
	_ infer.CustomCheck[VmArgs]             = (*Vm)(nil)
	_ infer.CustomRead[VmArgs, VmState]     = (*Vm)(nil)
	_ infer.CustomUpdate[VmArgs, VmState]   = (*Vm)(nil)
	_ infer.CustomDelete[VmState]           = (*Vm)(nil)
	_ infer.CustomDiff[VmArgs, VmState]     = (*Vm)(nil)
	_ infer.Annotated                       = (*Vm)(nil)
)

func (v *Vm) Annotate(a infer.Annotator) {
	a.Describe(&v, "A persistent Linux VM on exe.dev.")
	a.SetToken("index", "Vm")
}

func (a *VmArgs) Annotate(an infer.Annotator) {
	an.Describe(&a.Name, "VM name. Auto-generated by exe.dev if omitted. Changing this replaces the VM.")
	an.Describe(&a.Image, "Container image (e.g. ubuntu:22.04). Changing this replaces the VM.")
	an.Describe(&a.CPU, "Number of CPUs.")
	an.Describe(&a.Memory, "Memory allocation, e.g. 4GB.")
	an.Describe(&a.Disk, "Disk size, e.g. 20GB. Can only grow; shrinking replaces the VM.")
	an.Describe(&a.Tags, "Tags applied to the VM.")
	an.Describe(&a.Env, "Environment variables. Changing these replaces the VM.")
	an.Describe(&a.SetupScript, "Setup script run on first boot. Changing this replaces the VM.")
	an.Describe(&a.Command, "Container command: auto, none, or a custom command. Changing this replaces the VM.")
	an.Describe(&a.Comment, "Short note about the VM (max 200 bytes).")
	an.Describe(&a.Integrations, "Integrations to attach at creation. Changing these replaces the VM.")
	an.Describe(&a.Prompt, "Initial prompt sent to Shelley after creation (requires the exeuntu image). Applied only at create time.")
	an.Describe(&a.RegistryAuth, "Private registry credentials as USERNAME:PASSWORD for the --image registry.")
	an.Describe(&a.NoEmail, "Suppress the creation email notification.")
	an.Describe(&a.Public, "Make the HTTP proxy publicly accessible. Defaults to private.")
	an.Describe(&a.Port, "Container port the HTTP proxy forwards to.")
	an.Describe(&a.ReceiveEmail, "Enable inbound email delivery to the VM.")
	an.Describe(&a.TeamAccess, "Allow team members SSH, Shelley, and web-proxy access to the VM.")
}

func (Vm) Check(ctx context.Context, req infer.CheckRequest) (infer.CheckResponse[VmArgs], error) {
	args, failures, err := infer.DefaultCheck[VmArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[VmArgs]{Inputs: args, Failures: failures}, err
	}
	if args.Memory != nil {
		norm, nerr := NormalizeSize(*args.Memory)
		if nerr != nil {
			failures = append(failures, p.CheckFailure{Property: "memory", Reason: nerr.Error()})
		} else {
			args.Memory = &norm
		}
	}
	if args.Disk != nil {
		norm, nerr := NormalizeSize(*args.Disk)
		if nerr != nil {
			failures = append(failures, p.CheckFailure{Property: "disk", Reason: nerr.Error()})
		} else {
			args.Disk = &norm
		}
	}
	return infer.CheckResponse[VmArgs]{Inputs: args, Failures: failures}, nil
}

func (Vm) Create(ctx context.Context, req infer.CreateRequest[VmArgs]) (infer.CreateResponse[VmState], error) {
	in := req.Inputs
	state := VmState{VmArgs: in}

	if req.DryRun {
		return infer.CreateResponse[VmState]{ID: deref(in.Name), Output: state}, nil
	}

	client := clientFromContext(ctx)
	vm, err := client.Create(ctx, toCreateArgs(in))
	if err != nil {
		return infer.CreateResponse[VmState]{}, err
	}
	if final, ok := waitForReady(ctx, client, vm.Name); ok {
		vm = final
	}
	if err := applyShare(ctx, client, vm.Name, nil, in); err != nil {
		return infer.CreateResponse[VmState]{}, err
	}
	applyVM(&state, vm)
	return infer.CreateResponse[VmState]{ID: vm.Name, Output: state}, nil
}

// applyShare reconciles the public/port share settings from old -> new. old is nil
// on create (defaults: private, no explicit port).
func applyShare(ctx context.Context, client *Client, name string, old *VmArgs, in VmArgs) error {
	oldPort, oldPublic := (*int)(nil), (*bool)(nil)
	if old != nil {
		oldPort, oldPublic = old.Port, old.Public
	}
	if in.Port != nil && !intEq(in.Port, oldPort) {
		if err := client.SharePort(ctx, name, *in.Port); err != nil {
			return err
		}
	}
	if in.Public != nil && (oldPublic == nil || *in.Public != *oldPublic) {
		if err := client.ShareSetPublic(ctx, name, *in.Public); err != nil {
			return err
		}
	}

	var oldEmail, oldAccess *bool
	if old != nil {
		oldEmail, oldAccess = old.ReceiveEmail, old.TeamAccess
	}
	if in.ReceiveEmail != nil && (oldEmail == nil || *in.ReceiveEmail != *oldEmail) {
		if err := client.ShareReceiveEmail(ctx, name, *in.ReceiveEmail); err != nil {
			return err
		}
	}
	if in.TeamAccess != nil && (oldAccess == nil || *in.TeamAccess != *oldAccess) {
		if err := client.ShareAccess(ctx, name, *in.TeamAccess); err != nil {
			return err
		}
	}
	return nil
}

func (Vm) Read(ctx context.Context, req infer.ReadRequest[VmArgs, VmState]) (infer.ReadResponse[VmArgs, VmState], error) {
	client := clientFromContext(ctx)
	name := req.ID
	if name == "" {
		name = req.State.VMName
	}
	vm, ok, err := client.Get(ctx, name)
	if err != nil {
		return infer.ReadResponse[VmArgs, VmState]{}, err
	}
	if !ok {
		return infer.ReadResponse[VmArgs, VmState]{}, nil // empty ID signals deletion
	}

	state := req.State
	if state.VMName == "" {
		state.VmArgs = req.Inputs
	}
	applyVM(&state, vm)
	return infer.ReadResponse[VmArgs, VmState]{ID: vm.Name, Inputs: state.VmArgs, State: state}, nil
}

func (Vm) Update(ctx context.Context, req infer.UpdateRequest[VmArgs, VmState]) (infer.UpdateResponse[VmState], error) {
	in := req.Inputs
	old := req.State
	state := old
	state.VmArgs = in

	if req.DryRun {
		return infer.UpdateResponse[VmState]{Output: state}, nil
	}

	client := clientFromContext(ctx)
	name := old.VMName

	var cpu *int
	var mem, disk string
	if !intEq(in.CPU, old.CPU) {
		cpu = in.CPU
	}
	if !strEq(in.Memory, old.Memory) {
		mem = deref(in.Memory)
	}
	if !strEq(in.Disk, old.Disk) {
		disk = deref(in.Disk)
	}
	if cpu != nil || mem != "" || disk != "" {
		if err := client.Resize(ctx, name, cpu, mem, disk); err != nil {
			return infer.UpdateResponse[VmState]{}, err
		}
	}

	add, remove := diffTags(old.Tags, in.Tags)
	if err := client.AddTags(ctx, name, add); err != nil {
		return infer.UpdateResponse[VmState]{}, err
	}
	if err := client.RemoveTags(ctx, name, remove); err != nil {
		return infer.UpdateResponse[VmState]{}, err
	}

	if !strEq(in.Comment, old.Comment) {
		if err := client.SetComment(ctx, name, deref(in.Comment)); err != nil {
			return infer.UpdateResponse[VmState]{}, err
		}
	}

	if err := applyShare(ctx, client, name, &old.VmArgs, in); err != nil {
		return infer.UpdateResponse[VmState]{}, err
	}

	if vm, ok, err := client.Get(ctx, name); err == nil && ok {
		applyVM(&state, vm)
	}
	return infer.UpdateResponse[VmState]{Output: state}, nil
}

func (Vm) Delete(ctx context.Context, req infer.DeleteRequest[VmState]) (infer.DeleteResponse, error) {
	client := clientFromContext(ctx)
	name := req.State.VMName
	if name == "" {
		name = req.ID
	}
	return infer.DeleteResponse{}, client.Delete(ctx, name)
}

func (Vm) Diff(_ context.Context, req infer.DiffRequest[VmArgs, VmState]) (infer.DiffResponse, error) {
	in := req.Inputs
	old := req.State.VmArgs
	diff := map[string]p.PropertyDiff{}

	replace := func(field string, changed bool) {
		if changed {
			diff[field] = p.PropertyDiff{Kind: p.UpdateReplace}
		}
	}
	update := func(field string, changed bool) {
		if changed {
			diff[field] = p.PropertyDiff{Kind: p.Update}
		}
	}

	replace("name", !strEq(in.Name, old.Name))
	replace("image", !strEq(in.Image, old.Image))
	replace("setupScript", !strEq(in.SetupScript, old.SetupScript))
	replace("command", !strEq(in.Command, old.Command))
	replace("env", !envEq(in.Env, old.Env))
	replace("integrations", !sliceEq(in.Integrations, old.Integrations))

	update("cpu", !intEq(in.CPU, old.CPU))
	update("memory", !strEq(in.Memory, old.Memory))
	update("comment", !strEq(in.Comment, old.Comment))
	update("tags", !setEq(in.Tags, old.Tags))
	update("port", !intEq(in.Port, old.Port))
	update("public", boolPtr(in.Public) != boolPtr(old.Public))
	update("receiveEmail", boolPtr(in.ReceiveEmail) != boolPtr(old.ReceiveEmail))
	update("teamAccess", boolPtr(in.TeamAccess) != boolPtr(old.TeamAccess))

	// Disk grows in place; shrinking is not supported so it forces a replace.
	if !strEq(in.Disk, old.Disk) {
		kind := p.Update
		if in.Disk != nil && old.Disk != nil {
			newGB, e1 := SizeToGB(*in.Disk)
			oldGB, e2 := SizeToGB(*old.Disk)
			if e1 == nil && e2 == nil && newGB < oldGB {
				kind = p.UpdateReplace
			}
		}
		diff["disk"] = p.PropertyDiff{Kind: kind}
	}

	// A same-name replace would collide on create, so delete first.
	deleteBeforeReplace := false
	if strEq(in.Name, old.Name) {
		for _, d := range diff {
			if d.Kind == p.UpdateReplace || d.Kind == p.AddReplace || d.Kind == p.DeleteReplace {
				deleteBeforeReplace = true
				break
			}
		}
	}

	return infer.DiffResponse{
		HasChanges:          len(diff) > 0,
		DetailedDiff:        diff,
		DeleteBeforeReplace: deleteBeforeReplace,
	}, nil
}

func toCreateArgs(in VmArgs) CreateArgs {
	return CreateArgs{
		Name:         deref(in.Name),
		Image:        deref(in.Image),
		CPU:          in.CPU,
		Memory:       deref(in.Memory),
		Disk:         deref(in.Disk),
		Tags:         in.Tags,
		Env:          in.Env,
		SetupScript:  deref(in.SetupScript),
		Command:      deref(in.Command),
		Comment:      deref(in.Comment),
		Integrations: in.Integrations,
		Prompt:       deref(in.Prompt),
		RegistryAuth: deref(in.RegistryAuth),
		NoEmail:      in.NoEmail != nil && *in.NoEmail,
	}
}

func applyVM(state *VmState, vm *VM) {
	state.VMName = vm.Name
	state.HTTPSURL = vm.HTTPSURL
	state.SSHDest = vm.SSHDest
	state.Region = vm.Region
	state.RegionDisplay = vm.RegionDisplay
	state.Status = vm.Status
	state.AllocatedCPUs = vm.AllocatedCPUs
	state.MemoryBytes = vm.MemoryBytes
	state.DiskBytes = vm.DiskBytes
}

func waitForReady(ctx context.Context, client *Client, name string) (*VM, bool) {
	deadline := time.Now().Add(90 * time.Second)
	var last *VM
	for {
		vm, ok, err := client.Get(ctx, name)
		if err == nil && ok {
			last = vm
			switch vm.Status {
			case "running", "stopped", "error", "failed":
				return vm, true
			}
		}
		if time.Now().After(deadline) || ctx.Err() != nil {
			return last, last != nil
		}
		select {
		case <-ctx.Done():
			return last, last != nil
		case <-time.After(3 * time.Second):
		}
	}
}

func diffTags(old, new []string) (add, remove []string) {
	oldSet, newSet := toSet(old), toSet(new)
	for t := range newSet {
		if !oldSet[t] {
			add = append(add, t)
		}
	}
	for t := range oldSet {
		if !newSet[t] {
			remove = append(remove, t)
		}
	}
	return add, remove
}

func toSet(s []string) map[string]bool {
	m := make(map[string]bool, len(s))
	for _, v := range s {
		m[v] = true
	}
	return m
}

func deref(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

func strEq(a, b *string) bool { return deref(a) == deref(b) }

func intEq(a, b *int) bool {
	if a == nil || b == nil {
		return a == b
	}
	return *a == *b
}

func sliceEq(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func setEq(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	as, bs := toSet(a), toSet(b)
	for k := range as {
		if !bs[k] {
			return false
		}
	}
	return true
}

func envEq(a, b map[string]string) bool {
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if bv, ok := b[k]; !ok || bv != v {
			return false
		}
	}
	return true
}
