// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package exedev

import (
	"context"
	"reflect"

	"github.com/firstatlast/pulumi-exedev/sdk/go/exedev/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Look up an existing exe.dev VM by name.
func LookupVm(ctx *pulumi.Context, args *LookupVmArgs, opts ...pulumi.InvokeOption) (*LookupVmResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupVmResult
	err := ctx.Invoke("exedev:index:getVm", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupVmArgs struct {
	// Name of the VM to look up.
	Name string `pulumi:"name"`
}

type LookupVmResult struct {
	AllocatedCpus int      `pulumi:"allocatedCpus"`
	Comment       string   `pulumi:"comment"`
	DiskBytes     int      `pulumi:"diskBytes"`
	HttpsUrl      string   `pulumi:"httpsUrl"`
	Image         string   `pulumi:"image"`
	MemoryBytes   int      `pulumi:"memoryBytes"`
	Region        string   `pulumi:"region"`
	RegionDisplay string   `pulumi:"regionDisplay"`
	SshDest       string   `pulumi:"sshDest"`
	Status        string   `pulumi:"status"`
	Tags          []string `pulumi:"tags"`
	VmName        string   `pulumi:"vmName"`
}

func LookupVmOutput(ctx *pulumi.Context, args LookupVmOutputArgs, opts ...pulumi.InvokeOption) LookupVmResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupVmResultOutput, error) {
			args := v.(LookupVmArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("exedev:index:getVm", args, LookupVmResultOutput{}, options).(LookupVmResultOutput), nil
		}).(LookupVmResultOutput)
}

type LookupVmOutputArgs struct {
	// Name of the VM to look up.
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupVmOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVmArgs)(nil)).Elem()
}

type LookupVmResultOutput struct{ *pulumi.OutputState }

func (LookupVmResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVmResult)(nil)).Elem()
}

func (o LookupVmResultOutput) ToLookupVmResultOutput() LookupVmResultOutput {
	return o
}

func (o LookupVmResultOutput) ToLookupVmResultOutputWithContext(ctx context.Context) LookupVmResultOutput {
	return o
}

func (o LookupVmResultOutput) AllocatedCpus() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmResult) int { return v.AllocatedCpus }).(pulumi.IntOutput)
}

func (o LookupVmResultOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.Comment }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) DiskBytes() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmResult) int { return v.DiskBytes }).(pulumi.IntOutput)
}

func (o LookupVmResultOutput) HttpsUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.HttpsUrl }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) Image() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.Image }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) MemoryBytes() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmResult) int { return v.MemoryBytes }).(pulumi.IntOutput)
}

func (o LookupVmResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) RegionDisplay() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.RegionDisplay }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) SshDest() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.SshDest }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupVmResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o LookupVmResultOutput) VmName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.VmName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupVmResultOutput{})
}
