// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package exedev

import (
	"context"
	"reflect"

	"errors"
	"github.com/firstatlast/pulumi-exedev/sdk/go/exedev/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// An exe.dev integration. Currently models the http-proxy type, which injects auth/headers into requests from attached VMs to a target URL.
type Integration struct {
	pulumi.CustomResourceState

	// Where the integration is mounted: vm:<name>, tag:<name>, or auto:all.
	Attachments pulumi.StringArrayOutput `pulumi:"attachments"`
	// Bearer token to inject (shorthand for an Authorization: Bearer header).
	Bearer pulumi.StringPtrOutput `pulumi:"bearer"`
	// Free-form comment stored with the integration.
	Comment pulumi.StringPtrOutput `pulumi:"comment"`
	// Headers to inject, as name->value.
	Headers pulumi.StringMapOutput `pulumi:"headers"`
	// Integration name (unique). Changing this replaces the integration.
	Name pulumi.StringOutput `pulumi:"name"`
	// Create the http-proxy with no injected authentication.
	NoAuth       pulumi.BoolPtrOutput `pulumi:"noAuth"`
	ResolvedType pulumi.StringOutput  `pulumi:"resolvedType"`
	// Target URL the http-proxy forwards to.
	Target pulumi.StringPtrOutput `pulumi:"target"`
	// Integration type. Defaults to http-proxy. Changing this replaces the integration.
	Type pulumi.StringPtrOutput `pulumi:"type"`
}

// NewIntegration registers a new resource with the given unique name, arguments, and options.
func NewIntegration(ctx *pulumi.Context,
	name string, args *IntegrationArgs, opts ...pulumi.ResourceOption) (*Integration, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Type == nil {
		args.Type = pulumi.StringPtr("http-proxy")
	}
	if args.Bearer != nil {
		args.Bearer = pulumi.ToSecret(args.Bearer).(pulumi.StringPtrInput)
	}
	if args.Headers != nil {
		args.Headers = pulumi.ToSecret(args.Headers).(pulumi.StringMapInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"bearer",
		"headers",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Integration
	err := ctx.RegisterResource("exedev:index:Integration", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIntegration gets an existing Integration resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIntegration(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IntegrationState, opts ...pulumi.ResourceOption) (*Integration, error) {
	var resource Integration
	err := ctx.ReadResource("exedev:index:Integration", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Integration resources.
type integrationState struct {
}

type IntegrationState struct {
}

func (IntegrationState) ElementType() reflect.Type {
	return reflect.TypeOf((*integrationState)(nil)).Elem()
}

type integrationArgs struct {
	// Where the integration is mounted: vm:<name>, tag:<name>, or auto:all.
	Attachments []string `pulumi:"attachments"`
	// Bearer token to inject (shorthand for an Authorization: Bearer header).
	Bearer *string `pulumi:"bearer"`
	// Free-form comment stored with the integration.
	Comment *string `pulumi:"comment"`
	// Headers to inject, as name->value.
	Headers map[string]string `pulumi:"headers"`
	// Integration name (unique). Changing this replaces the integration.
	Name string `pulumi:"name"`
	// Create the http-proxy with no injected authentication.
	NoAuth *bool `pulumi:"noAuth"`
	// Target URL the http-proxy forwards to.
	Target *string `pulumi:"target"`
	// Integration type. Defaults to http-proxy. Changing this replaces the integration.
	Type *string `pulumi:"type"`
}

// The set of arguments for constructing a Integration resource.
type IntegrationArgs struct {
	// Where the integration is mounted: vm:<name>, tag:<name>, or auto:all.
	Attachments pulumi.StringArrayInput
	// Bearer token to inject (shorthand for an Authorization: Bearer header).
	Bearer pulumi.StringPtrInput
	// Free-form comment stored with the integration.
	Comment pulumi.StringPtrInput
	// Headers to inject, as name->value.
	Headers pulumi.StringMapInput
	// Integration name (unique). Changing this replaces the integration.
	Name pulumi.StringInput
	// Create the http-proxy with no injected authentication.
	NoAuth pulumi.BoolPtrInput
	// Target URL the http-proxy forwards to.
	Target pulumi.StringPtrInput
	// Integration type. Defaults to http-proxy. Changing this replaces the integration.
	Type pulumi.StringPtrInput
}

func (IntegrationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*integrationArgs)(nil)).Elem()
}

type IntegrationInput interface {
	pulumi.Input

	ToIntegrationOutput() IntegrationOutput
	ToIntegrationOutputWithContext(ctx context.Context) IntegrationOutput
}

func (*Integration) ElementType() reflect.Type {
	return reflect.TypeOf((**Integration)(nil)).Elem()
}

func (i *Integration) ToIntegrationOutput() IntegrationOutput {
	return i.ToIntegrationOutputWithContext(context.Background())
}

func (i *Integration) ToIntegrationOutputWithContext(ctx context.Context) IntegrationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IntegrationOutput)
}

// IntegrationArrayInput is an input type that accepts IntegrationArray and IntegrationArrayOutput values.
// You can construct a concrete instance of `IntegrationArrayInput` via:
//
//	IntegrationArray{ IntegrationArgs{...} }
type IntegrationArrayInput interface {
	pulumi.Input

	ToIntegrationArrayOutput() IntegrationArrayOutput
	ToIntegrationArrayOutputWithContext(context.Context) IntegrationArrayOutput
}

type IntegrationArray []IntegrationInput

func (IntegrationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Integration)(nil)).Elem()
}

func (i IntegrationArray) ToIntegrationArrayOutput() IntegrationArrayOutput {
	return i.ToIntegrationArrayOutputWithContext(context.Background())
}

func (i IntegrationArray) ToIntegrationArrayOutputWithContext(ctx context.Context) IntegrationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IntegrationArrayOutput)
}

// IntegrationMapInput is an input type that accepts IntegrationMap and IntegrationMapOutput values.
// You can construct a concrete instance of `IntegrationMapInput` via:
//
//	IntegrationMap{ "key": IntegrationArgs{...} }
type IntegrationMapInput interface {
	pulumi.Input

	ToIntegrationMapOutput() IntegrationMapOutput
	ToIntegrationMapOutputWithContext(context.Context) IntegrationMapOutput
}

type IntegrationMap map[string]IntegrationInput

func (IntegrationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Integration)(nil)).Elem()
}

func (i IntegrationMap) ToIntegrationMapOutput() IntegrationMapOutput {
	return i.ToIntegrationMapOutputWithContext(context.Background())
}

func (i IntegrationMap) ToIntegrationMapOutputWithContext(ctx context.Context) IntegrationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IntegrationMapOutput)
}

type IntegrationOutput struct{ *pulumi.OutputState }

func (IntegrationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Integration)(nil)).Elem()
}

func (o IntegrationOutput) ToIntegrationOutput() IntegrationOutput {
	return o
}

func (o IntegrationOutput) ToIntegrationOutputWithContext(ctx context.Context) IntegrationOutput {
	return o
}

// Where the integration is mounted: vm:<name>, tag:<name>, or auto:all.
func (o IntegrationOutput) Attachments() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Integration) pulumi.StringArrayOutput { return v.Attachments }).(pulumi.StringArrayOutput)
}

// Bearer token to inject (shorthand for an Authorization: Bearer header).
func (o IntegrationOutput) Bearer() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Integration) pulumi.StringPtrOutput { return v.Bearer }).(pulumi.StringPtrOutput)
}

// Free-form comment stored with the integration.
func (o IntegrationOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Integration) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// Headers to inject, as name->value.
func (o IntegrationOutput) Headers() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Integration) pulumi.StringMapOutput { return v.Headers }).(pulumi.StringMapOutput)
}

// Integration name (unique). Changing this replaces the integration.
func (o IntegrationOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Integration) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Create the http-proxy with no injected authentication.
func (o IntegrationOutput) NoAuth() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Integration) pulumi.BoolPtrOutput { return v.NoAuth }).(pulumi.BoolPtrOutput)
}

func (o IntegrationOutput) ResolvedType() pulumi.StringOutput {
	return o.ApplyT(func(v *Integration) pulumi.StringOutput { return v.ResolvedType }).(pulumi.StringOutput)
}

// Target URL the http-proxy forwards to.
func (o IntegrationOutput) Target() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Integration) pulumi.StringPtrOutput { return v.Target }).(pulumi.StringPtrOutput)
}

// Integration type. Defaults to http-proxy. Changing this replaces the integration.
func (o IntegrationOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Integration) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

type IntegrationArrayOutput struct{ *pulumi.OutputState }

func (IntegrationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Integration)(nil)).Elem()
}

func (o IntegrationArrayOutput) ToIntegrationArrayOutput() IntegrationArrayOutput {
	return o
}

func (o IntegrationArrayOutput) ToIntegrationArrayOutputWithContext(ctx context.Context) IntegrationArrayOutput {
	return o
}

func (o IntegrationArrayOutput) Index(i pulumi.IntInput) IntegrationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Integration {
		return vs[0].([]*Integration)[vs[1].(int)]
	}).(IntegrationOutput)
}

type IntegrationMapOutput struct{ *pulumi.OutputState }

func (IntegrationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Integration)(nil)).Elem()
}

func (o IntegrationMapOutput) ToIntegrationMapOutput() IntegrationMapOutput {
	return o
}

func (o IntegrationMapOutput) ToIntegrationMapOutputWithContext(ctx context.Context) IntegrationMapOutput {
	return o
}

func (o IntegrationMapOutput) MapIndex(k pulumi.StringInput) IntegrationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Integration {
		return vs[0].(map[string]*Integration)[vs[1].(string)]
	}).(IntegrationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IntegrationInput)(nil)).Elem(), &Integration{})
	pulumi.RegisterInputType(reflect.TypeOf((*IntegrationArrayInput)(nil)).Elem(), IntegrationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*IntegrationMapInput)(nil)).Elem(), IntegrationMap{})
	pulumi.RegisterOutputType(IntegrationOutput{})
	pulumi.RegisterOutputType(IntegrationArrayOutput{})
	pulumi.RegisterOutputType(IntegrationMapOutput{})
}
