// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package exedev

import (
	"context"
	"reflect"

	"errors"
	"github.com/firstatlast/pulumi-exedev/sdk/go/exedev/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A shareable HTTPS access link for a VM.
type ShareLink struct {
	pulumi.CustomResourceState

	Token pulumi.StringOutput `pulumi:"token"`
	Url   pulumi.StringOutput `pulumi:"url"`
	// Name of the VM to create a share link for. Changing this replaces the link.
	Vm pulumi.StringOutput `pulumi:"vm"`
}

// NewShareLink registers a new resource with the given unique name, arguments, and options.
func NewShareLink(ctx *pulumi.Context,
	name string, args *ShareLinkArgs, opts ...pulumi.ResourceOption) (*ShareLink, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Vm == nil {
		return nil, errors.New("invalid value for required argument 'Vm'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ShareLink
	err := ctx.RegisterResource("exedev:index:ShareLink", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetShareLink gets an existing ShareLink resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetShareLink(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ShareLinkState, opts ...pulumi.ResourceOption) (*ShareLink, error) {
	var resource ShareLink
	err := ctx.ReadResource("exedev:index:ShareLink", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ShareLink resources.
type shareLinkState struct {
}

type ShareLinkState struct {
}

func (ShareLinkState) ElementType() reflect.Type {
	return reflect.TypeOf((*shareLinkState)(nil)).Elem()
}

type shareLinkArgs struct {
	// Name of the VM to create a share link for. Changing this replaces the link.
	Vm string `pulumi:"vm"`
}

// The set of arguments for constructing a ShareLink resource.
type ShareLinkArgs struct {
	// Name of the VM to create a share link for. Changing this replaces the link.
	Vm pulumi.StringInput
}

func (ShareLinkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*shareLinkArgs)(nil)).Elem()
}

type ShareLinkInput interface {
	pulumi.Input

	ToShareLinkOutput() ShareLinkOutput
	ToShareLinkOutputWithContext(ctx context.Context) ShareLinkOutput
}

func (*ShareLink) ElementType() reflect.Type {
	return reflect.TypeOf((**ShareLink)(nil)).Elem()
}

func (i *ShareLink) ToShareLinkOutput() ShareLinkOutput {
	return i.ToShareLinkOutputWithContext(context.Background())
}

func (i *ShareLink) ToShareLinkOutputWithContext(ctx context.Context) ShareLinkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ShareLinkOutput)
}

// ShareLinkArrayInput is an input type that accepts ShareLinkArray and ShareLinkArrayOutput values.
// You can construct a concrete instance of `ShareLinkArrayInput` via:
//
//	ShareLinkArray{ ShareLinkArgs{...} }
type ShareLinkArrayInput interface {
	pulumi.Input

	ToShareLinkArrayOutput() ShareLinkArrayOutput
	ToShareLinkArrayOutputWithContext(context.Context) ShareLinkArrayOutput
}

type ShareLinkArray []ShareLinkInput

func (ShareLinkArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ShareLink)(nil)).Elem()
}

func (i ShareLinkArray) ToShareLinkArrayOutput() ShareLinkArrayOutput {
	return i.ToShareLinkArrayOutputWithContext(context.Background())
}

func (i ShareLinkArray) ToShareLinkArrayOutputWithContext(ctx context.Context) ShareLinkArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ShareLinkArrayOutput)
}

// ShareLinkMapInput is an input type that accepts ShareLinkMap and ShareLinkMapOutput values.
// You can construct a concrete instance of `ShareLinkMapInput` via:
//
//	ShareLinkMap{ "key": ShareLinkArgs{...} }
type ShareLinkMapInput interface {
	pulumi.Input

	ToShareLinkMapOutput() ShareLinkMapOutput
	ToShareLinkMapOutputWithContext(context.Context) ShareLinkMapOutput
}

type ShareLinkMap map[string]ShareLinkInput

func (ShareLinkMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ShareLink)(nil)).Elem()
}

func (i ShareLinkMap) ToShareLinkMapOutput() ShareLinkMapOutput {
	return i.ToShareLinkMapOutputWithContext(context.Background())
}

func (i ShareLinkMap) ToShareLinkMapOutputWithContext(ctx context.Context) ShareLinkMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ShareLinkMapOutput)
}

type ShareLinkOutput struct{ *pulumi.OutputState }

func (ShareLinkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ShareLink)(nil)).Elem()
}

func (o ShareLinkOutput) ToShareLinkOutput() ShareLinkOutput {
	return o
}

func (o ShareLinkOutput) ToShareLinkOutputWithContext(ctx context.Context) ShareLinkOutput {
	return o
}

func (o ShareLinkOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *ShareLink) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

func (o ShareLinkOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *ShareLink) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

// Name of the VM to create a share link for. Changing this replaces the link.
func (o ShareLinkOutput) Vm() pulumi.StringOutput {
	return o.ApplyT(func(v *ShareLink) pulumi.StringOutput { return v.Vm }).(pulumi.StringOutput)
}

type ShareLinkArrayOutput struct{ *pulumi.OutputState }

func (ShareLinkArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ShareLink)(nil)).Elem()
}

func (o ShareLinkArrayOutput) ToShareLinkArrayOutput() ShareLinkArrayOutput {
	return o
}

func (o ShareLinkArrayOutput) ToShareLinkArrayOutputWithContext(ctx context.Context) ShareLinkArrayOutput {
	return o
}

func (o ShareLinkArrayOutput) Index(i pulumi.IntInput) ShareLinkOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ShareLink {
		return vs[0].([]*ShareLink)[vs[1].(int)]
	}).(ShareLinkOutput)
}

type ShareLinkMapOutput struct{ *pulumi.OutputState }

func (ShareLinkMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ShareLink)(nil)).Elem()
}

func (o ShareLinkMapOutput) ToShareLinkMapOutput() ShareLinkMapOutput {
	return o
}

func (o ShareLinkMapOutput) ToShareLinkMapOutputWithContext(ctx context.Context) ShareLinkMapOutput {
	return o
}

func (o ShareLinkMapOutput) MapIndex(k pulumi.StringInput) ShareLinkOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ShareLink {
		return vs[0].(map[string]*ShareLink)[vs[1].(string)]
	}).(ShareLinkOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ShareLinkInput)(nil)).Elem(), &ShareLink{})
	pulumi.RegisterInputType(reflect.TypeOf((*ShareLinkArrayInput)(nil)).Elem(), ShareLinkArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ShareLinkMapInput)(nil)).Elem(), ShareLinkMap{})
	pulumi.RegisterOutputType(ShareLinkOutput{})
	pulumi.RegisterOutputType(ShareLinkArrayOutput{})
	pulumi.RegisterOutputType(ShareLinkMapOutput{})
}
