// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package exedev

import (
	"context"
	"reflect"

	"github.com/firstatlast/pulumi-exedev/sdk/go/exedev/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A persistent Linux VM on exe.dev.
type Vm struct {
	pulumi.CustomResourceState

	AllocatedCpus pulumi.IntOutput `pulumi:"allocatedCpus"`
	// Container command: auto, none, or a custom command. Changing this replaces the VM.
	Command pulumi.StringPtrOutput `pulumi:"command"`
	// Short note about the VM (max 200 bytes).
	Comment pulumi.StringPtrOutput `pulumi:"comment"`
	// Number of CPUs.
	Cpu pulumi.IntPtrOutput `pulumi:"cpu"`
	// Disk size, e.g. 20GB. Can only grow; shrinking replaces the VM.
	Disk      pulumi.StringPtrOutput `pulumi:"disk"`
	DiskBytes pulumi.IntOutput       `pulumi:"diskBytes"`
	// Environment variables. Changing these replaces the VM.
	Env      pulumi.StringMapOutput `pulumi:"env"`
	HttpsUrl pulumi.StringOutput    `pulumi:"httpsUrl"`
	// Container image (e.g. ubuntu:22.04). Changing this replaces the VM.
	Image pulumi.StringPtrOutput `pulumi:"image"`
	// Integrations to attach at creation. Changing these replaces the VM.
	Integrations pulumi.StringArrayOutput `pulumi:"integrations"`
	// Memory allocation, e.g. 4GB.
	Memory      pulumi.StringPtrOutput `pulumi:"memory"`
	MemoryBytes pulumi.IntOutput       `pulumi:"memoryBytes"`
	// VM name. Auto-generated by exe.dev if omitted. Changing this replaces the VM.
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// Suppress the creation email notification.
	NoEmail pulumi.BoolPtrOutput `pulumi:"noEmail"`
	// Initial prompt sent to Shelley after creation (requires the exeuntu image). Applied only at create time.
	Prompt        pulumi.StringPtrOutput `pulumi:"prompt"`
	Region        pulumi.StringOutput    `pulumi:"region"`
	RegionDisplay pulumi.StringOutput    `pulumi:"regionDisplay"`
	// Private registry credentials as USERNAME:PASSWORD for the --image registry.
	RegistryAuth pulumi.StringPtrOutput `pulumi:"registryAuth"`
	// Setup script run on first boot. Changing this replaces the VM.
	SetupScript pulumi.StringPtrOutput `pulumi:"setupScript"`
	SshDest     pulumi.StringOutput    `pulumi:"sshDest"`
	Status      pulumi.StringOutput    `pulumi:"status"`
	// Tags applied to the VM.
	Tags   pulumi.StringArrayOutput `pulumi:"tags"`
	VmName pulumi.StringOutput      `pulumi:"vmName"`
}

// NewVm registers a new resource with the given unique name, arguments, and options.
func NewVm(ctx *pulumi.Context,
	name string, args *VmArgs, opts ...pulumi.ResourceOption) (*Vm, error) {
	if args == nil {
		args = &VmArgs{}
	}

	if args.RegistryAuth != nil {
		args.RegistryAuth = pulumi.ToSecret(args.RegistryAuth).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"registryAuth",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Vm
	err := ctx.RegisterResource("exedev:index:Vm", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVm gets an existing Vm resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVm(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VmState, opts ...pulumi.ResourceOption) (*Vm, error) {
	var resource Vm
	err := ctx.ReadResource("exedev:index:Vm", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Vm resources.
type vmState struct {
}

type VmState struct {
}

func (VmState) ElementType() reflect.Type {
	return reflect.TypeOf((*vmState)(nil)).Elem()
}

type vmArgs struct {
	// Container command: auto, none, or a custom command. Changing this replaces the VM.
	Command *string `pulumi:"command"`
	// Short note about the VM (max 200 bytes).
	Comment *string `pulumi:"comment"`
	// Number of CPUs.
	Cpu *int `pulumi:"cpu"`
	// Disk size, e.g. 20GB. Can only grow; shrinking replaces the VM.
	Disk *string `pulumi:"disk"`
	// Environment variables. Changing these replaces the VM.
	Env map[string]string `pulumi:"env"`
	// Container image (e.g. ubuntu:22.04). Changing this replaces the VM.
	Image *string `pulumi:"image"`
	// Integrations to attach at creation. Changing these replaces the VM.
	Integrations []string `pulumi:"integrations"`
	// Memory allocation, e.g. 4GB.
	Memory *string `pulumi:"memory"`
	// VM name. Auto-generated by exe.dev if omitted. Changing this replaces the VM.
	Name *string `pulumi:"name"`
	// Suppress the creation email notification.
	NoEmail *bool `pulumi:"noEmail"`
	// Initial prompt sent to Shelley after creation (requires the exeuntu image). Applied only at create time.
	Prompt *string `pulumi:"prompt"`
	// Private registry credentials as USERNAME:PASSWORD for the --image registry.
	RegistryAuth *string `pulumi:"registryAuth"`
	// Setup script run on first boot. Changing this replaces the VM.
	SetupScript *string `pulumi:"setupScript"`
	// Tags applied to the VM.
	Tags []string `pulumi:"tags"`
}

// The set of arguments for constructing a Vm resource.
type VmArgs struct {
	// Container command: auto, none, or a custom command. Changing this replaces the VM.
	Command pulumi.StringPtrInput
	// Short note about the VM (max 200 bytes).
	Comment pulumi.StringPtrInput
	// Number of CPUs.
	Cpu pulumi.IntPtrInput
	// Disk size, e.g. 20GB. Can only grow; shrinking replaces the VM.
	Disk pulumi.StringPtrInput
	// Environment variables. Changing these replaces the VM.
	Env pulumi.StringMapInput
	// Container image (e.g. ubuntu:22.04). Changing this replaces the VM.
	Image pulumi.StringPtrInput
	// Integrations to attach at creation. Changing these replaces the VM.
	Integrations pulumi.StringArrayInput
	// Memory allocation, e.g. 4GB.
	Memory pulumi.StringPtrInput
	// VM name. Auto-generated by exe.dev if omitted. Changing this replaces the VM.
	Name pulumi.StringPtrInput
	// Suppress the creation email notification.
	NoEmail pulumi.BoolPtrInput
	// Initial prompt sent to Shelley after creation (requires the exeuntu image). Applied only at create time.
	Prompt pulumi.StringPtrInput
	// Private registry credentials as USERNAME:PASSWORD for the --image registry.
	RegistryAuth pulumi.StringPtrInput
	// Setup script run on first boot. Changing this replaces the VM.
	SetupScript pulumi.StringPtrInput
	// Tags applied to the VM.
	Tags pulumi.StringArrayInput
}

func (VmArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*vmArgs)(nil)).Elem()
}

type VmInput interface {
	pulumi.Input

	ToVmOutput() VmOutput
	ToVmOutputWithContext(ctx context.Context) VmOutput
}

func (*Vm) ElementType() reflect.Type {
	return reflect.TypeOf((**Vm)(nil)).Elem()
}

func (i *Vm) ToVmOutput() VmOutput {
	return i.ToVmOutputWithContext(context.Background())
}

func (i *Vm) ToVmOutputWithContext(ctx context.Context) VmOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VmOutput)
}

// VmArrayInput is an input type that accepts VmArray and VmArrayOutput values.
// You can construct a concrete instance of `VmArrayInput` via:
//
//	VmArray{ VmArgs{...} }
type VmArrayInput interface {
	pulumi.Input

	ToVmArrayOutput() VmArrayOutput
	ToVmArrayOutputWithContext(context.Context) VmArrayOutput
}

type VmArray []VmInput

func (VmArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Vm)(nil)).Elem()
}

func (i VmArray) ToVmArrayOutput() VmArrayOutput {
	return i.ToVmArrayOutputWithContext(context.Background())
}

func (i VmArray) ToVmArrayOutputWithContext(ctx context.Context) VmArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VmArrayOutput)
}

// VmMapInput is an input type that accepts VmMap and VmMapOutput values.
// You can construct a concrete instance of `VmMapInput` via:
//
//	VmMap{ "key": VmArgs{...} }
type VmMapInput interface {
	pulumi.Input

	ToVmMapOutput() VmMapOutput
	ToVmMapOutputWithContext(context.Context) VmMapOutput
}

type VmMap map[string]VmInput

func (VmMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Vm)(nil)).Elem()
}

func (i VmMap) ToVmMapOutput() VmMapOutput {
	return i.ToVmMapOutputWithContext(context.Background())
}

func (i VmMap) ToVmMapOutputWithContext(ctx context.Context) VmMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VmMapOutput)
}

type VmOutput struct{ *pulumi.OutputState }

func (VmOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Vm)(nil)).Elem()
}

func (o VmOutput) ToVmOutput() VmOutput {
	return o
}

func (o VmOutput) ToVmOutputWithContext(ctx context.Context) VmOutput {
	return o
}

func (o VmOutput) AllocatedCpus() pulumi.IntOutput {
	return o.ApplyT(func(v *Vm) pulumi.IntOutput { return v.AllocatedCpus }).(pulumi.IntOutput)
}

// Container command: auto, none, or a custom command. Changing this replaces the VM.
func (o VmOutput) Command() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringPtrOutput { return v.Command }).(pulumi.StringPtrOutput)
}

// Short note about the VM (max 200 bytes).
func (o VmOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// Number of CPUs.
func (o VmOutput) Cpu() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Vm) pulumi.IntPtrOutput { return v.Cpu }).(pulumi.IntPtrOutput)
}

// Disk size, e.g. 20GB. Can only grow; shrinking replaces the VM.
func (o VmOutput) Disk() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringPtrOutput { return v.Disk }).(pulumi.StringPtrOutput)
}

func (o VmOutput) DiskBytes() pulumi.IntOutput {
	return o.ApplyT(func(v *Vm) pulumi.IntOutput { return v.DiskBytes }).(pulumi.IntOutput)
}

// Environment variables. Changing these replaces the VM.
func (o VmOutput) Env() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringMapOutput { return v.Env }).(pulumi.StringMapOutput)
}

func (o VmOutput) HttpsUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringOutput { return v.HttpsUrl }).(pulumi.StringOutput)
}

// Container image (e.g. ubuntu:22.04). Changing this replaces the VM.
func (o VmOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringPtrOutput { return v.Image }).(pulumi.StringPtrOutput)
}

// Integrations to attach at creation. Changing these replaces the VM.
func (o VmOutput) Integrations() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringArrayOutput { return v.Integrations }).(pulumi.StringArrayOutput)
}

// Memory allocation, e.g. 4GB.
func (o VmOutput) Memory() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringPtrOutput { return v.Memory }).(pulumi.StringPtrOutput)
}

func (o VmOutput) MemoryBytes() pulumi.IntOutput {
	return o.ApplyT(func(v *Vm) pulumi.IntOutput { return v.MemoryBytes }).(pulumi.IntOutput)
}

// VM name. Auto-generated by exe.dev if omitted. Changing this replaces the VM.
func (o VmOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// Suppress the creation email notification.
func (o VmOutput) NoEmail() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Vm) pulumi.BoolPtrOutput { return v.NoEmail }).(pulumi.BoolPtrOutput)
}

// Initial prompt sent to Shelley after creation (requires the exeuntu image). Applied only at create time.
func (o VmOutput) Prompt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringPtrOutput { return v.Prompt }).(pulumi.StringPtrOutput)
}

func (o VmOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

func (o VmOutput) RegionDisplay() pulumi.StringOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringOutput { return v.RegionDisplay }).(pulumi.StringOutput)
}

// Private registry credentials as USERNAME:PASSWORD for the --image registry.
func (o VmOutput) RegistryAuth() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringPtrOutput { return v.RegistryAuth }).(pulumi.StringPtrOutput)
}

// Setup script run on first boot. Changing this replaces the VM.
func (o VmOutput) SetupScript() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringPtrOutput { return v.SetupScript }).(pulumi.StringPtrOutput)
}

func (o VmOutput) SshDest() pulumi.StringOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringOutput { return v.SshDest }).(pulumi.StringOutput)
}

func (o VmOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Tags applied to the VM.
func (o VmOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o VmOutput) VmName() pulumi.StringOutput {
	return o.ApplyT(func(v *Vm) pulumi.StringOutput { return v.VmName }).(pulumi.StringOutput)
}

type VmArrayOutput struct{ *pulumi.OutputState }

func (VmArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Vm)(nil)).Elem()
}

func (o VmArrayOutput) ToVmArrayOutput() VmArrayOutput {
	return o
}

func (o VmArrayOutput) ToVmArrayOutputWithContext(ctx context.Context) VmArrayOutput {
	return o
}

func (o VmArrayOutput) Index(i pulumi.IntInput) VmOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Vm {
		return vs[0].([]*Vm)[vs[1].(int)]
	}).(VmOutput)
}

type VmMapOutput struct{ *pulumi.OutputState }

func (VmMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Vm)(nil)).Elem()
}

func (o VmMapOutput) ToVmMapOutput() VmMapOutput {
	return o
}

func (o VmMapOutput) ToVmMapOutputWithContext(ctx context.Context) VmMapOutput {
	return o
}

func (o VmMapOutput) MapIndex(k pulumi.StringInput) VmOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Vm {
		return vs[0].(map[string]*Vm)[vs[1].(string)]
	}).(VmOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VmInput)(nil)).Elem(), &Vm{})
	pulumi.RegisterInputType(reflect.TypeOf((*VmArrayInput)(nil)).Elem(), VmArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VmMapInput)(nil)).Elem(), VmMap{})
	pulumi.RegisterOutputType(VmOutput{})
	pulumi.RegisterOutputType(VmArrayOutput{})
	pulumi.RegisterOutputType(VmMapOutput{})
}
