// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/firstatlast/pulumi-exedev/sdk/go/exedev/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Override for the exe.dev exec endpoint.
func GetEndpoint(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "exedev:endpoint")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("https://exe.dev/exec", nil, "EXEDEV_ENDPOINT"); d != nil {
		value = d.(string)
	}
	return value
}

// exe.dev bearer API token. Generate with `ssh exe.dev ssh-key generate-api-key --exp=30d`.
func GetToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "exedev:token")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "EXEDEV_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}
