// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("exedev");

/**
 * Override for the exe.dev exec endpoint.
 */
export declare const endpoint: string;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint") ?? (utilities.getEnv("EXEDEV_ENDPOINT") || "https://exe.dev/exec");
    },
    enumerable: true,
});

/**
 * exe.dev bearer API token. Generate with `ssh exe.dev ssh-key generate-api-key --exp=30d`.
 */
export declare const token: string;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token") ?? (utilities.getEnv("EXEDEV_TOKEN") || "");
    },
    enumerable: true,
});

