// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A custom domain linked to an exe.dev VM.
 */
export class Domain extends pulumi.CustomResource {
    /**
     * Get an existing Domain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Domain {
        return new Domain(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'exedev:index:Domain';

    /**
     * Returns true if the given object is an instance of Domain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Domain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Domain.__pulumiType;
    }

    /**
     * The custom hostname (a CNAME you already point at the VM). Changing this replaces the domain.
     */
    declare public readonly hostname: pulumi.Output<string>;
    declare public /*out*/ readonly verified: pulumi.Output<boolean>;
    /**
     * Name of the VM to attach the domain to. Changing this replaces the domain.
     */
    declare public readonly vm: pulumi.Output<string>;
    /**
     * Issue a wildcard (*.<parent>) certificate via DNS-01 delegation.
     */
    declare public readonly wildcard: pulumi.Output<boolean | undefined>;

    /**
     * Create a Domain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.hostname === undefined && !opts.urn) {
                throw new Error("Missing required property 'hostname'");
            }
            if (args?.vm === undefined && !opts.urn) {
                throw new Error("Missing required property 'vm'");
            }
            resourceInputs["hostname"] = args?.hostname;
            resourceInputs["vm"] = args?.vm;
            resourceInputs["wildcard"] = args?.wildcard;
            resourceInputs["verified"] = undefined /*out*/;
        } else {
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["verified"] = undefined /*out*/;
            resourceInputs["vm"] = undefined /*out*/;
            resourceInputs["wildcard"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Domain.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Domain resource.
 */
export interface DomainArgs {
    /**
     * The custom hostname (a CNAME you already point at the VM). Changing this replaces the domain.
     */
    hostname: pulumi.Input<string>;
    /**
     * Name of the VM to attach the domain to. Changing this replaces the domain.
     */
    vm: pulumi.Input<string>;
    /**
     * Issue a wildcard (*.<parent>) certificate via DNS-01 delegation.
     */
    wildcard?: pulumi.Input<boolean | undefined>;
}
