// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Look up an existing exe.dev VM by name.
 */
export function getVm(args: GetVmArgs, opts?: pulumi.InvokeOptions): Promise<GetVmResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("exedev:index:getVm", {
        "name": args.name,
    }, opts);
}

export interface GetVmArgs {
    /**
     * Name of the VM to look up.
     */
    name: string;
}

export interface GetVmResult {
    readonly allocatedCpus: number;
    readonly comment: string;
    readonly diskBytes: number;
    readonly httpsUrl: string;
    readonly image: string;
    readonly memoryBytes: number;
    readonly region: string;
    readonly regionDisplay: string;
    readonly sshDest: string;
    readonly status: string;
    readonly tags: string[];
    readonly vmName: string;
}
/**
 * Look up an existing exe.dev VM by name.
 */
export function getVmOutput(args: GetVmOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetVmResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("exedev:index:getVm", {
        "name": args.name,
    }, opts);
}

export interface GetVmOutputArgs {
    /**
     * Name of the VM to look up.
     */
    name: pulumi.Input<string>;
}
