// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { DomainArgs } from "./domain";
export type Domain = import("./domain").Domain;
export const Domain: typeof import("./domain").Domain = null as any;
utilities.lazyLoad(exports, ["Domain"], () => require("./domain"));

export { GetVmArgs, GetVmResult, GetVmOutputArgs } from "./getVm";
export const getVm: typeof import("./getVm").getVm = null as any;
export const getVmOutput: typeof import("./getVm").getVmOutput = null as any;
utilities.lazyLoad(exports, ["getVm","getVmOutput"], () => require("./getVm"));

export { IntegrationArgs } from "./integration";
export type Integration = import("./integration").Integration;
export const Integration: typeof import("./integration").Integration = null as any;
utilities.lazyLoad(exports, ["Integration"], () => require("./integration"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { ShareArgs } from "./share";
export type Share = import("./share").Share;
export const Share: typeof import("./share").Share = null as any;
utilities.lazyLoad(exports, ["Share"], () => require("./share"));

export { ShareLinkArgs } from "./shareLink";
export type ShareLink = import("./shareLink").ShareLink;
export const ShareLink: typeof import("./shareLink").ShareLink = null as any;
utilities.lazyLoad(exports, ["ShareLink"], () => require("./shareLink"));

export { SshKeyArgs } from "./sshKey";
export type SshKey = import("./sshKey").SshKey;
export const SshKey: typeof import("./sshKey").SshKey = null as any;
utilities.lazyLoad(exports, ["SshKey"], () => require("./sshKey"));

export { TeamMemberArgs } from "./teamMember";
export type TeamMember = import("./teamMember").TeamMember;
export const TeamMember: typeof import("./teamMember").TeamMember = null as any;
utilities.lazyLoad(exports, ["TeamMember"], () => require("./teamMember"));

export { VmArgs } from "./vm";
export type Vm = import("./vm").Vm;
export const Vm: typeof import("./vm").Vm = null as any;
utilities.lazyLoad(exports, ["Vm"], () => require("./vm"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "exedev:index:Domain":
                return new Domain(name, <any>undefined, { urn })
            case "exedev:index:Integration":
                return new Integration(name, <any>undefined, { urn })
            case "exedev:index:Share":
                return new Share(name, <any>undefined, { urn })
            case "exedev:index:ShareLink":
                return new ShareLink(name, <any>undefined, { urn })
            case "exedev:index:SshKey":
                return new SshKey(name, <any>undefined, { urn })
            case "exedev:index:TeamMember":
                return new TeamMember(name, <any>undefined, { urn })
            case "exedev:index:Vm":
                return new Vm(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("exedev", "index", _module)
pulumi.runtime.registerResourcePackage("exedev", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:exedev") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
