// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * An exe.dev integration. Currently models the http-proxy type, which injects auth/headers into requests from attached VMs to a target URL.
 */
export class Integration extends pulumi.CustomResource {
    /**
     * Get an existing Integration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Integration {
        return new Integration(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'exedev:index:Integration';

    /**
     * Returns true if the given object is an instance of Integration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Integration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Integration.__pulumiType;
    }

    /**
     * Where the integration is mounted: vm:<name>, tag:<name>, or auto:all.
     */
    declare public readonly attachments: pulumi.Output<string[] | undefined>;
    /**
     * Bearer token to inject (shorthand for an Authorization: Bearer header).
     */
    declare public readonly bearer: pulumi.Output<string | undefined>;
    /**
     * Free-form comment stored with the integration.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * Headers to inject, as name->value.
     */
    declare public readonly headers: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Integration name (unique). Changing this replaces the integration.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Create the http-proxy with no injected authentication.
     */
    declare public readonly noAuth: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly resolvedType: pulumi.Output<string>;
    /**
     * Target URL the http-proxy forwards to.
     */
    declare public readonly target: pulumi.Output<string | undefined>;
    /**
     * Integration type. Defaults to http-proxy. Changing this replaces the integration.
     */
    declare public readonly type: pulumi.Output<string | undefined>;

    /**
     * Create a Integration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["attachments"] = args?.attachments;
            resourceInputs["bearer"] = args?.bearer ? pulumi.secret(args.bearer) : undefined;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["headers"] = args?.headers ? pulumi.secret(args.headers) : undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["noAuth"] = args?.noAuth;
            resourceInputs["target"] = args?.target;
            resourceInputs["type"] = (args?.type) ?? "http-proxy";
            resourceInputs["resolvedType"] = undefined /*out*/;
        } else {
            resourceInputs["attachments"] = undefined /*out*/;
            resourceInputs["bearer"] = undefined /*out*/;
            resourceInputs["comment"] = undefined /*out*/;
            resourceInputs["headers"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["noAuth"] = undefined /*out*/;
            resourceInputs["resolvedType"] = undefined /*out*/;
            resourceInputs["target"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["bearer", "headers"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Integration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Integration resource.
 */
export interface IntegrationArgs {
    /**
     * Where the integration is mounted: vm:<name>, tag:<name>, or auto:all.
     */
    attachments?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Bearer token to inject (shorthand for an Authorization: Bearer header).
     */
    bearer?: pulumi.Input<string | undefined>;
    /**
     * Free-form comment stored with the integration.
     */
    comment?: pulumi.Input<string | undefined>;
    /**
     * Headers to inject, as name->value.
     */
    headers?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Integration name (unique). Changing this replaces the integration.
     */
    name: pulumi.Input<string>;
    /**
     * Create the http-proxy with no injected authentication.
     */
    noAuth?: pulumi.Input<boolean | undefined>;
    /**
     * Target URL the http-proxy forwards to.
     */
    target?: pulumi.Input<string | undefined>;
    /**
     * Integration type. Defaults to http-proxy. Changing this replaces the integration.
     */
    type?: pulumi.Input<string | undefined>;
}
