// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'exedev';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Override for the exe.dev exec endpoint.
     */
    declare public readonly endpoint: pulumi.Output<string | undefined>;
    /**
     * exe.dev bearer API token. Generate with `ssh exe.dev ssh-key generate-api-key --exp=30d`.
     */
    declare public readonly token: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["endpoint"] = (args?.endpoint) ?? (utilities.getEnv("EXEDEV_ENDPOINT") || "https://exe.dev/exec");
            resourceInputs["token"] = (args?.token ? pulumi.secret(args.token) : undefined) ?? (utilities.getEnv("EXEDEV_TOKEN") || "");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Override for the exe.dev exec endpoint.
     */
    endpoint?: pulumi.Input<string | undefined>;
    /**
     * exe.dev bearer API token. Generate with `ssh exe.dev ssh-key generate-api-key --exp=30d`.
     */
    token?: pulumi.Input<string | undefined>;
}
