// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A shareable HTTPS access link for a VM.
 */
export class ShareLink extends pulumi.CustomResource {
    /**
     * Get an existing ShareLink resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ShareLink {
        return new ShareLink(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'exedev:index:ShareLink';

    /**
     * Returns true if the given object is an instance of ShareLink.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ShareLink {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ShareLink.__pulumiType;
    }

    declare public /*out*/ readonly token: pulumi.Output<string>;
    declare public /*out*/ readonly url: pulumi.Output<string>;
    /**
     * Name of the VM to create a share link for. Changing this replaces the link.
     */
    declare public readonly vm: pulumi.Output<string>;

    /**
     * Create a ShareLink resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ShareLinkArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.vm === undefined && !opts.urn) {
                throw new Error("Missing required property 'vm'");
            }
            resourceInputs["vm"] = args?.vm;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        } else {
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
            resourceInputs["vm"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ShareLink.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ShareLink resource.
 */
export interface ShareLinkArgs {
    /**
     * Name of the VM to create a share link for. Changing this replaces the link.
     */
    vm: pulumi.Input<string>;
}
