// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A persistent Linux VM on exe.dev.
 */
export class Vm extends pulumi.CustomResource {
    /**
     * Get an existing Vm resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Vm {
        return new Vm(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'exedev:index:Vm';

    /**
     * Returns true if the given object is an instance of Vm.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Vm {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Vm.__pulumiType;
    }

    declare public /*out*/ readonly allocatedCpus: pulumi.Output<number>;
    /**
     * Container command: auto, none, or a custom command. Changing this replaces the VM.
     */
    declare public readonly command: pulumi.Output<string | undefined>;
    /**
     * Short note about the VM (max 200 bytes).
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * Number of CPUs.
     */
    declare public readonly cpu: pulumi.Output<number | undefined>;
    /**
     * Disk size, e.g. 20GB. Can only grow; shrinking replaces the VM.
     */
    declare public readonly disk: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly diskBytes: pulumi.Output<number>;
    /**
     * Environment variables. Changing these replaces the VM.
     */
    declare public readonly env: pulumi.Output<{[key: string]: string} | undefined>;
    declare public /*out*/ readonly httpsUrl: pulumi.Output<string>;
    /**
     * Container image (e.g. ubuntu:22.04). Changing this replaces the VM.
     */
    declare public readonly image: pulumi.Output<string | undefined>;
    /**
     * Integrations to attach at creation. Changing these replaces the VM.
     */
    declare public readonly integrations: pulumi.Output<string[] | undefined>;
    /**
     * Memory allocation, e.g. 4GB.
     */
    declare public readonly memory: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly memoryBytes: pulumi.Output<number>;
    /**
     * VM name. Auto-generated by exe.dev if omitted. Changing this replaces the VM.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * Suppress the creation email notification.
     */
    declare public readonly noEmail: pulumi.Output<boolean | undefined>;
    /**
     * Container port the HTTP proxy forwards to.
     */
    declare public readonly port: pulumi.Output<number | undefined>;
    /**
     * Initial prompt sent to Shelley after creation (requires the exeuntu image). Applied only at create time.
     */
    declare public readonly prompt: pulumi.Output<string | undefined>;
    /**
     * Make the HTTP proxy publicly accessible. Defaults to private.
     */
    declare public readonly public: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly region: pulumi.Output<string>;
    declare public /*out*/ readonly regionDisplay: pulumi.Output<string>;
    /**
     * Private registry credentials as USERNAME:PASSWORD for the --image registry.
     */
    declare public readonly registryAuth: pulumi.Output<string | undefined>;
    /**
     * Setup script run on first boot. Changing this replaces the VM.
     */
    declare public readonly setupScript: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly sshDest: pulumi.Output<string>;
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Tags applied to the VM.
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    declare public /*out*/ readonly vmName: pulumi.Output<string>;

    /**
     * Create a Vm resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: VmArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["command"] = args?.command;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["cpu"] = args?.cpu;
            resourceInputs["disk"] = args?.disk;
            resourceInputs["env"] = args?.env;
            resourceInputs["image"] = args?.image;
            resourceInputs["integrations"] = args?.integrations;
            resourceInputs["memory"] = args?.memory;
            resourceInputs["name"] = args?.name;
            resourceInputs["noEmail"] = args?.noEmail;
            resourceInputs["port"] = args?.port;
            resourceInputs["prompt"] = args?.prompt;
            resourceInputs["public"] = args?.public;
            resourceInputs["registryAuth"] = args?.registryAuth ? pulumi.secret(args.registryAuth) : undefined;
            resourceInputs["setupScript"] = args?.setupScript;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["allocatedCpus"] = undefined /*out*/;
            resourceInputs["diskBytes"] = undefined /*out*/;
            resourceInputs["httpsUrl"] = undefined /*out*/;
            resourceInputs["memoryBytes"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["regionDisplay"] = undefined /*out*/;
            resourceInputs["sshDest"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["vmName"] = undefined /*out*/;
        } else {
            resourceInputs["allocatedCpus"] = undefined /*out*/;
            resourceInputs["command"] = undefined /*out*/;
            resourceInputs["comment"] = undefined /*out*/;
            resourceInputs["cpu"] = undefined /*out*/;
            resourceInputs["disk"] = undefined /*out*/;
            resourceInputs["diskBytes"] = undefined /*out*/;
            resourceInputs["env"] = undefined /*out*/;
            resourceInputs["httpsUrl"] = undefined /*out*/;
            resourceInputs["image"] = undefined /*out*/;
            resourceInputs["integrations"] = undefined /*out*/;
            resourceInputs["memory"] = undefined /*out*/;
            resourceInputs["memoryBytes"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["noEmail"] = undefined /*out*/;
            resourceInputs["port"] = undefined /*out*/;
            resourceInputs["prompt"] = undefined /*out*/;
            resourceInputs["public"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["regionDisplay"] = undefined /*out*/;
            resourceInputs["registryAuth"] = undefined /*out*/;
            resourceInputs["setupScript"] = undefined /*out*/;
            resourceInputs["sshDest"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["vmName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["registryAuth"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Vm.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Vm resource.
 */
export interface VmArgs {
    /**
     * Container command: auto, none, or a custom command. Changing this replaces the VM.
     */
    command?: pulumi.Input<string | undefined>;
    /**
     * Short note about the VM (max 200 bytes).
     */
    comment?: pulumi.Input<string | undefined>;
    /**
     * Number of CPUs.
     */
    cpu?: pulumi.Input<number | undefined>;
    /**
     * Disk size, e.g. 20GB. Can only grow; shrinking replaces the VM.
     */
    disk?: pulumi.Input<string | undefined>;
    /**
     * Environment variables. Changing these replaces the VM.
     */
    env?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Container image (e.g. ubuntu:22.04). Changing this replaces the VM.
     */
    image?: pulumi.Input<string | undefined>;
    /**
     * Integrations to attach at creation. Changing these replaces the VM.
     */
    integrations?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Memory allocation, e.g. 4GB.
     */
    memory?: pulumi.Input<string | undefined>;
    /**
     * VM name. Auto-generated by exe.dev if omitted. Changing this replaces the VM.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Suppress the creation email notification.
     */
    noEmail?: pulumi.Input<boolean | undefined>;
    /**
     * Container port the HTTP proxy forwards to.
     */
    port?: pulumi.Input<number | undefined>;
    /**
     * Initial prompt sent to Shelley after creation (requires the exeuntu image). Applied only at create time.
     */
    prompt?: pulumi.Input<string | undefined>;
    /**
     * Make the HTTP proxy publicly accessible. Defaults to private.
     */
    public?: pulumi.Input<boolean | undefined>;
    /**
     * Private registry credentials as USERNAME:PASSWORD for the --image registry.
     */
    registryAuth?: pulumi.Input<string | undefined>;
    /**
     * Setup script run on first boot. Changing this replaces the VM.
     */
    setupScript?: pulumi.Input<string | undefined>;
    /**
     * Tags applied to the VM.
     */
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
